# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Company_Creation.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateCompany(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 430)
        MainWindow.setMinimumSize(QtCore.QSize(403, 430))
        MainWindow.setMaximumSize(QtCore.QSize(403, 430))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 50, 221, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 80, 221, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 110, 171, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 0, 231, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 16pt \"Lucida Bright\";\n"
"color: rgb(255, 85, 127);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 61, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 61, 21))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 61, 21))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 61, 21))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 230, 221, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(2, "")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 140, 171, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 170, 171, 21))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 200, 171, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(120, 350, 161, 31))
        self.buttonBox.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 260, 101, 21))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_9.setObjectName("label_9")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(80, 290, 110, 22))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 290, 41, 21))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(220, 290, 21, 21))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 63 8pt \"Lucida Bright\";")
        self.label_11.setObjectName("label_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(260, 290, 110, 22))
        self.dateEdit_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.dateEdit_2.setObjectName("dateEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBACK = QtWidgets.QAction(MainWindow)
        self.actionBACK.setObjectName("actionBACK")
        self.menuMENU.addAction(self.actionBACK)
        self.menubar.addAction(self.menuMENU.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NAME"))
        self.label_2.setText(_translate("MainWindow", "PROPRITOR NAME"))
        self.label_3.setText(_translate("MainWindow", "COUNTRY"))
        self.label_4.setText(_translate("MainWindow", "COMPANY CREATION"))
        self.label_5.setText(_translate("MainWindow", "STATE"))
        self.label_6.setText(_translate("MainWindow", "PIN CODE"))
        self.label_7.setText(_translate("MainWindow", "PHONE No."))
        self.label_8.setText(_translate("MainWindow", "MAINTAIN"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Accounts Only"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Accounts With Inventory"))
        self.label_9.setText(_translate("MainWindow", "FINANCIAL YEAR"))
        self.label_10.setText(_translate("MainWindow", "FROM"))
        self.label_11.setText(_translate("MainWindow", "TO"))
        self.menuMENU.setTitle(_translate("MainWindow", "MENU"))
        self.actionBACK.setText(_translate("MainWindow", "BACK"))
